# Generated by Django 4.1 on 2024-09-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='username',
            field=models.CharField(default='patients', max_length=50),
        ),
    ]
