# Generated by Django 4.1 on 2024-09-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_blog_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
